// LCM type definitions
// This file automatically generated by lcm-dart.
// DO NOT MODIFY BY HAND!!!!

import 'dart:convert';
import 'dart:typed_data';
import 'package:lcm_dart/lcm_dart.dart';

class PointT implements LcmMessage {
  static const int LCM_FINGERPRINT = 0xae7e5fba5eeca11e;

  double x;
  double y;
  double z;

  PointT({
    required this.x,
    required this.y,
    required this.z,
  });

  @override
  int get lcmFingerprint => LCM_FINGERPRINT;

  @override
  void encode(LcmBuffer buf) {
    buf.putInt64(LCM_FINGERPRINT);
    buf.putFloat64(x);
    buf.putFloat64(y);
    buf.putFloat64(z);
  }

  static PointT decode(LcmBuffer buf) {
    final fingerprint = buf.getInt64();
    if (fingerprint != LCM_FINGERPRINT) {
      throw Exception('Invalid fingerprint');
    }

    final x = buf.getFloat64();
    final y = buf.getFloat64();
    final z = buf.getFloat64();

    return PointT(
      x: x,
      y: y,
      z: z,
    );
  }
}
