// LCM type definitions
// This file automatically generated by lcm-gen.
// DO NOT MODIFY BY HAND!!!!

import 'dart:convert';
import 'dart:typed_data';
import 'package:lcm_dart/lcm_dart.dart';

class point_t implements LcmMessage {
  static const int LCM_FINGERPRINT = 0x573f2fdd2f76508f;

  double x;
  double y;
  double z;

  point_t({
    required this.x,
    required this.y,
    required this.z,
  });

  @override
  int get lcmFingerprint => LCM_FINGERPRINT;

  @override
  void encode(LcmBuffer buf) {
    buf.putInt64(LCM_FINGERPRINT);
    buf.putFloat64(x);
    buf.putFloat64(y);
    buf.putFloat64(z);
  }

  static point_t decode(LcmBuffer buf) {
    final fingerprint = buf.getInt64();
    if (fingerprint != LCM_FINGERPRINT) {
      throw Exception('Invalid fingerprint. Received: $fingerprint; Expected: $LCM_FINGERPRINT');
    }

    final x = buf.getFloat64();
    final y = buf.getFloat64();
    final z = buf.getFloat64();

    return point_t(
      x: x,
      y: y,
      z: z,
    );
  }
}
